# Generated by Django 3.0.4 on 2020-04-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_artist_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='hometown',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
